apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-gateway-traces
  namespace: observability
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.112.0
  replicas: 1

  envFrom:
    - secretRef:
        name: otel-collector-config

  nodeSelector:
    "workload": "observability"

  config:
    receivers:
      kafka/traces:
        brokers: "${env:KAFKA_BROKERS}"
        topic: "${env:KAFKA_TRACES_TOPIC}"
        protocol_version: 2.0.0
        encoding: "otlp_proto"
        group_id: "${env:KAFKA_TRACES_GROUP_ID}"
        auth:
          tls:
            insecure_skip_verify: true
          sasl:
            mechanism: "SCRAM-SHA-512"
            username: "${env:KAFKA_USERNAME}"
            password: "${env:KAFKA_PASSWORD}"

    processors:
      transform:
        trace_statements:
          - context: span
            statements:
              # parent_id 없는 root span에 강제로 속성 넣기 (정제)
              - set(attributes["collector.gateway"], "true")
              # 비어있는 service name guard
              - set(resource.attributes["service.name"], "unknown-service") where resource.attributes["service.name"] == nil

      tail_sampling:
        decision_wait: 5s
        num_traces: 5000
        expected_new_traces_per_sec: 200
        policies:
          - name: error-policy
            type: status_code
            status_code:
              status_codes: [ERROR]

          - name: high-latency
            type: latency
            latency:
              threshold_ms: 1000   # 1초 넘는 요청 모두 수집

          - name: probabilistic-default
            type: probabilistic
            probabilistic:
              sampling_percentage: 1

      batch:
        timeout: 1s
        send_batch_size: 8192

    exporters:
      otlp/tempo:
        endpoint: "tempo:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [kafka/traces]
          processors: [transform, tail_sampling, batch]
          exporters: [otlp/tempo]