apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-ksm
  namespace: observability
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.112.0
  replicas: 1

  serviceAccount: otel-collector-producer

  # observability nodepool에 배포
  nodeSelector:
    "workload": "observability"

  resources:
    limits:
      cpu: 200m
      memory: 128Mi

  config:
    receivers:
      prometheus/ksm:
        config:
          scrape_configs:
            - job_name: "kube-state-metrics"
              static_configs:
                - targets:
                    - "kube-state-metrics.kube-system.svc:8080"

    processors:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25

      batch:
        timeout: 5s
        send_batch_size: 1024

      k8sattributes:
        auth_type: serviceAccount
        filter:
          node_from_env_var: K8S_NODE_NAME
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.container.name
            - k8s.node.name

    exporters:
      otlphttp/mimir:
        metrics_endpoint: "http://mimir:9009/otlp/v1/metrics"
        tls:
          insecure: true
        headers:
          X-Scope-OrgID: "goormdotcom"

      debug:
        verbosity: normal
    service:
      pipelines:
        metrics/kubeletstats:
          receivers: [prometheus/ksm]
          processors: [memory_limiter, k8sattributes, batch]
          exporters: [otlphttp/mimir, debug]
