apiVersion: v1
kind: Pod
metadata:
  name: curl-debug
  namespace: observability
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "3600"]
  restartPolicy: Never
