apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: goorm-app-secret-store
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-operator
            namespace: external-secrets
