apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-producer-role
rules:
  - apiGroups: [""]
    resources:
      - "pods"
      - "pods/status"
      - "namespaces"
      - "nodes"
      - "nodes/proxy"
      - "nodes/stats"
      - "nodes/metrics"
    verbs:
      - "get"
      - "watch"
      - "list"

  - apiGroups: ["apps"]
    resources:
      - "replicasets"
      - "deployments"
    verbs:
      - "get"
      - "list"
      - "watch"

  - apiGroups: ["extensions"]
    resources:
      - "replicasets"
      - "deployments"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-producer-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector-producer-role
subjects:
  - kind: ServiceAccount
    name: otel-collector-producer
    namespace: observability
