apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otel-collector-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: goorm-app-secret-store
    kind: ClusterSecretStore
  target:
    name: otel-collector-config
  data:
    - secretKey: KAFKA_USERNAME
      remoteRef:
        key: goorm/msa/secret
        property: kafka.username

    - secretKey: KAFKA_PASSWORD
      remoteRef:
        key: goorm/msa/secret
        property: kafka.password

    - secretKey: KAFKA_BROKERS
      remoteRef:
        key: goorm/msa/secret
        property: kafka.brokers

    - secretKey: KAFKA_LOGS_TOPIC
      remoteRef:
        key: goorm/msa/secret
        property: kafka.logs.topic

    - secretKey: KAFKA_LOGS_GROUP_ID
      remoteRef:
        key: goorm/msa/secret
        property: kafka.logs.group_id

    - secretKey: KAFKA_TRACES_TOPIC
      remoteRef:
        key: goorm/msa/secret
        property: kafka.traces.topic

    - secretKey: KAFKA_TRACES_GROUP_ID
      remoteRef:
        key: goorm/msa/secret
        property: kafka.traces.group_id

    - secretKey: KAFKA_METRICS_TOPIC
      remoteRef:
        key: goorm/msa/secret
        property: kafka.metrics.topic

    - secretKey: KAFKA_METRICS_GROUP_ID
      remoteRef:
        key: goorm/msa/secret
        property: kafka.metrics.group_id
